title: Meu Blog Pessoal
email: pauloalbertoweiss@gmail.com
description: Um blog sobre desenvolvimento web e tecnologia
baseurl: ""
url: "http://localhost:4000"
github_pauloweiss: https://github.com/pauloweiss/meu-blog-pessoal.git
baseurl: ""ss 

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed