title: Meu Blog Pessoal
email: pauloalbertoweiss@gmail.com
description: Um blog sobre desenvolvimento web e tecnologia
baseurl: ""
url: "http://localhost:4000"
github_pauloweiss: "https://pauloweiss.github.io"
baseurl: ""ss 

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed